// src/common/enums/audit-action.enum.ts
export enum AuditAction {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  LOGIN = 'LOGIN',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  EXPORT_REPORT = 'EXPORT_REPORT',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
}
